<?php
$this->title = $this->translate('title_adminstration_r_languages_listing');
$this->headTitle($this->title);

$this->headScript()->appendFile($this->baseUrl() . '/js/administration/rlanguages/RLanguageManager.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/administration/rlanguages/index.js');
$bCreateEditIsAllowed = Phoenix_Auth_User::mvcActionIsAllowed('administration','rlanguages','loadrlanguageeditionpopup')  && Phoenix_Auth_User::mvcActionIsAllowed('administration','rlanguages','saverlanguagedata');
$bDeleteIsAllowed = Phoenix_Auth_User::mvcActionIsAllowed('administration','rlanguages','deleterlanguagerecord');

?>

<div id="actions-bar">
    <div class="unit size1of5">
        <h1 class="page-title"><?php echo $this->title; ?></h1>
        <?php if($bCreateEditIsAllowed){ ?>
        <input href="#" id="btn-add-new-language" type="button" data-language-addition-popup-title="<?php echo $this->translate('label_title_language_addition_popup_title') ?>" class="btn btn-orange btn-big" value="<?php echo $this->translate('button_add_new_language_label'); ?>" />
        <?php } ?>
    </div>
    <div class="unit size3of5">
        <div class="search">
            <form method="get" id="languages_form" action ="<?php echo $this->url(array('module' => 'administration', 'controller' => 'rlanguages', 'action' => 'index'), null, true) ?>" >
                <input type="text" name="findword" class="form-input" value="<?php echo isset($this->findword) ? $this->findword : ''; ?>" placeholder="<?php echo $this->translate('placeholder_search'); ?>" autocomplete="off" />
                <input type="submit" value="<?php echo $this->translate('OK'); ?>" class="btn btn-orange" />
                <input type="button" value="<?php echo $this->translate('Recherche avancée'); ?>" class="btn btn-big btn-adsearch" id="btn-adsearch" />
            </form>
        </div>
    </div>
</div>
<div id="site-content">
    <div class="content-list">
        <div class="list-actions">
            <div class="unit col">
                <a class="icon icon-32 icon-excel" href="<?php echo $this->url(array('format' => 'csv'), null, false) . '?' . $_SERVER['QUERY_STRING'] ?>" title="<?php echo $this->translate('Exporter au format Excel'); ?>"><?php echo $this->translate('Exporter au format Excel'); ?></a>
            </div>
            <div class="unit rightUnit">
                <div class="unit col">
                    <?php echo $this->NotifySearch()->link() ?>
                </div>
                <div class="unit">
                    <?php echo $this->paginationControl($this->paginator, 'Sliding', '/partials/pagination.phtml'); ?>
                </div>
            </div>
        </div>
        <table class="list list-main">
            <thead>
                <tr>
                    <th width="26" class="column-noborder"></th>
                    <th width="26" class="column-noborder"></th>
                    <th>
                        <?php echo My_View_Helper_Html::UrlOrderBy('r_lang_code', $this->translate('label_code')); ?>
                    </th>
                    <th>
                        <?php echo My_View_Helper_Html::UrlOrderBy('r_lang_libelle', $this->translate('label_language_label')); ?>
                    </th>
                    <th>
                        <?php echo My_View_Helper_Html::UrlOrderBy('r_lang_has_traduction_devis', $this->translate('label_has_quotation_translation_column')); ?>
                    </th>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $aLanguage): ?>
                    <tr class="<?php echo $this->cycle(array('', 'alt'))->next() ?>">
                        <td>
                            <?php if($bDeleteIsAllowed){ ?>
                            <a href="#delete" class="icon-list icon-delete" data-language-code="<?php echo $aLanguage['r_lang_code']; ?>" delete-language-record-confirmation-message="<?php echo $this->translate('text_confirm_language_record_deletion') . ' : ' . $aLanguage['r_lang_libelle'] ?>" title="<?php echo $this->translate('link_delete_language'); ?>"><?php echo $this->translate('link_delete_language'); ?></a>
                            <?php } ?>
                        </td>
                        <td>
                            <?php if($bCreateEditIsAllowed){ ?>
                            <a href="#edit" class="icon-list icon-edit" data-language-edition-popup-title="<?php echo $this->translate('title_edition'); ?>" data-language-code="<?php echo $aLanguage['r_lang_code']; ?>" title="<?php echo $this->translate('link_edit_language'); ?>"><?php echo $this->translate('link_edit_language'); ?></a>
                            <?php } ?>
                        </td>
                        <td align="left"><?php echo $aLanguage['r_lang_code']; ?></td>
                        <td align="left"><?php echo $aLanguage['r_lang_libelle']; ?></td>
                        <td align="left"><?php echo $aLanguage['r_lang_has_traduction_devis']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<div id="id-dialog-search" title="<?php echo $this->translate('Recherche avancée'); ?>" style="display:none;">
    <form action="<?php echo $this->BaseUrl() ?>/administration/rlanguages/index" method="GET">
        <div class="section-bd">
            <div class="line form-line">
                <label class="unit size1of2 form-label" for="id-r-lang-code-id"><?php echo $this->translate('label_code'); ?> :</label>
                <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'find_r_lang_code', 'class' => 'unit size1of2 form-input lastUnit')) ?>
            </div>
            <div class="line form-line">
                <label class="unit size1of2 form-label" for="id-r-lang-libelle"><?php echo $this->translate('label_language_label'); ?> :</label>
                <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'find_r_lang_libelle', 'class' => 'unit size1of2 form-input lastUnit')) ?>
            </div>
            <div class="line form-line">
                <label class="unit size1of2 form-label" for="id-r-lang-has-traduction-devis"><?php echo $this->translate('label_has_quotation_translation_column'); ?> :</label>
                <?php echo Phoenix_View_Helper_Html::checkbox(array('name' => 'find_r_lang_has_traduction_devis', 'value' => 1)) ?>
            </div>
        </div>
        <div class="text-center">
            <input type="submit" name="findbyfields" value="<?php echo $this->translate('Recherche'); ?>" class="btn btn-orange">
        </div>
    </form>
</div>
