<form id="language-update-form" action="<?php echo $this->url(array('module' => 'administration', 'controller' => 'rlanguages', 'action' => 'saverlanguagedata')) ?>" method="post">
    <?php echo Phoenix_View_Helper_Html::input(array('type' => 'hidden', 'name' => 'old_r_lang_code', 'value' => ($this->rLanguage) ? $this->rLanguage->getRLangCode() : '')) ?>
    <div class="line form-line">
        <label class="unit size1of3 form-label" for='id-r-lang-code-id'><?php echo $this->translate('label_code'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'id' => 'id-r-lang-code', 'name' => 'r_lang_code', 'disabled' => ($this->rLanguage) ? true : false, 'class' => 'unit size2of3 form-input lastUnit', 'value' => ($this->rLanguage) ? $this->rLanguage->getRLangCode() : '')) ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of3 form-label" for='id-r-lang-libelle'><?php echo $this->translate('label_language_label'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'id' => 'id-r-lang-libelle', 'name' => 'r_lang_libelle', 'class' => 'unit size2of3 form-input lastUnit', 'value' => ($this->rLanguage) ? $this->rLanguage->getRLangLibelle() : '')) ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of3 form-label" for='id-r-lang-has-traduction-devis'><?php echo $this->translate('label_has_quotation_translation'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::checkbox(array('id' => 'id-r-lang-has-traduction-devis', 'name' => 'r_lang_has_traduction_devis', 'value' => 1, 'default_value' => ($this->rLanguage) ? $this->rLanguage->getRLangHasTraductionDevis() : '')) ?>
    </div>
    <div class="text-center">
        <input type="submit" value="<?php echo $this->translate('Valider'); ?>" class="btn btn-orange">
    </div>
</form>