<!-- DIALOG / CHOIX PAYS -->
<form method="post"  id="id_form_pays_int">
    <div class="form-section" style="height:220px;overflow:auto;">
        <table class="list list-main">
            <thead>
                <tr>
                    <th width="40" class="check-column"><input id="check_all_dest" type="checkbox" /></th>
                    <th><span class="notsortable"><?php echo $this->translate('Nom'); ?></span></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->countries as $country) { ?>
                    <tr class="tr-check <?php echo $this->cycle(array('', 'alt'))->next() ?>">
                        <td class="check-column">
                            <input class="checkbox_dest" type="checkbox" name="lnk_op_country_id[]" value="<?php echo $country['r_country_id'] ?>" <?php echo $country['is_selected'] == 1 ? 'checked="checked"' : '' ?>>
                        </td>
                        <td><?php echo $country['r_country_name'] ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <div class="text-center">
        <input type="hidden" name="op_id" value="<?php echo $this->op_id ?>" />
        <input type="hidden" name="submit_pays_inter" value="1" />
        <input type="submit" value="<?php echo $this->translate('Valider'); ?>" class="btn btn-orange" />
    </div>
</form>


<script type="text/javascript">

    $(document).ready(function () {
        $('#check_all_dest').bindCheckboxes('checkbox_dest');

        AjaxComponent.ajaxForm('/operation/description/popupmodifpaysinter', 'id_form_pays_int', 'id_block_paysinter',
                function () {
                    $('#id_popupmodifpaysinter').dialog('close');
                })
    })

</script>