<form id="country-calling-code-update-form" action="<?php echo $this->url(array('module' => 'administration', 'controller' => 'rcountriescallingcodes', 'action' => 'savercountrycallingcodedata')) ?>" method="post">
    <?php echo Phoenix_View_Helper_Html::input(array('type' => 'hidden', 'name' => 'r_country_calling_code_id', 'value' => ($this->rCountryCallingCode) ? $this->rCountryCallingCode->getRCountryCallingCodeId() : '')) ?>
    <div class="line form-line">
        <label class="unit size1of3 form-label" for='id-r-country-calling-code'><?php echo $this->translate('label_country_calling_code'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'id' => 'id-r-country-calling-code', 'name' => 'r_country_calling_code', 'class' => 'unit size2of3 form-input lastUnit', 'value' => ($this->rCountryCallingCode) ? $this->rCountryCallingCode->getRCountryCallingCode() : '')) ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of3 form-label" for='id-r-country-calling-code-actif'><?php echo $this->translate('label_actif'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::checkbox(array('id' => 'id-r-country-calling-code-actif', 'name' => 'r_country_calling_code_actif', 'value' => 1, 'default_value' => ($this->rCountryCallingCode) ? $this->rCountryCallingCode->getRcountryCallingCodeActif() : '')) ?>
    </div>
    <div class="text-center">
        <input type="submit" value="<?php echo $this->translate('Valider'); ?>" class="btn btn-orange">
    </div>
</form>
