<!-- DIALOG / DELETE -->
<form id="id_form_validate_task" action="<?php echo $this->url(array('module' => 'operation', 'controller' => 'taches', 'action' => 'validate')) ?>" method="post">
    <input type="hidden" name="submit_validate_task" value="1">
    <input type="hidden" name="op_task_id" value="<?php echo $this->task_data->getOpTaskId(); ?>">

    <div class="line form-line">
        <span class="unit size1of2 form-label"><?php echo $this->translate('N° OP');?> :</span>
        <span class="unit size1of2 form-text"><b><?php echo $this->task_data->getOperations()->getOpNumber(); ?></b></span>
    </div>
    
    <div class="line form-line">
        <span class="unit size1of2 form-label"><?php echo $this->translate('Type de tâche');?> :</span>
        <?php echo Phoenix_View_Helper_Html::selectFromTable('r_operation_tasks_type', array('disabled' => True, 'name' => 'op_task_type_id', 'id' => 'op_task_type_id', 'value' => $this->task_data->getOpTaskTypeId(), 'class' => 'form-select unit size1of2 lastUnit'), array('value' => 'r_op_task_type_id', 'name' => 'r_op_task_type_libelle'), array('default_label' => $this->translate('choisir').'...')); ?>
    </div>
    
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('Date de réalisation');?> :</label>
        <div class="unit size1of4 date">
            <?php echo Phoenix_View_Helper_Html::input(array('name' => 'op_task_done', 'id' => 'op_task_done', 'value' => $this->task_data->getOpTaskDone('d/m/Y'), 'class' => 'date-input', 'placeholder' => $this->translate('JJ/MM/AAAA'), 'maxlenght' => '10', 'required' => True)); ?>
        </div>
    </div>
    
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('Temps passé');?> :</label>
        <div class="unit size1of2 lastUnit">
            <?php echo Phoenix_View_Helper_Html::input(array('name' => 'op_task_duree_reelle', 'id' => 'op_task_duree_reelle', 'value' => $this->task_data->getOpTaskDureeReelle(), 'class' => 'form-input size1of4')); ?>&nbsp;<?php echo $this->translate('minutes'); ?>
        </div>
    </div>
    
    <div class="line form-line">
        <label class="unit size1of1 form-label" for=""><?php echo $this->translate('Commentaire');?> :</label>
    </div>
    
    <div class="line form-section">
        <textarea name="op_task_comments" id="op_task_comments" rows="8" cols="60" class="form-textarea unit size1of1 lastUnit"><?php echo $this->task_data->getOpTaskComments(); ?></textarea>
    </div>
    
    <div class="text-center">
        <input type="submit" value="<?php echo $this->translate('Valider'); ?>" class="btn btn-orange">
    </div>
</form>


<script language="javascript">
    $(document).ready(function(){
        $('#id_form_validate_task').ajaxForm({
            divId:'id_dialog_validate_task'
        });
        
        $('#op_task_done').datepicker({
		showOn: "button",
		buttonText: "",
		altFormat: "yyyy-mm-dd"
	});
    });
</script>