<?php
$this->title = $this->translate('Paramètrage de compte');
$this->headTitle($this->title);

echo $this->FlashMessenger('error');
echo $this->FlashMessenger('default');
?>

<div id="site-content">
    <div id="content-bd">
        <div class="line">
            <div class="unit size1of2">
                <div class="line box">
                    <div class="box-hd">
                        <h2 class="box-title"><?php echo $this->translate('Ajouter une signature'); ?></h2>
                    </div>
                    <div class="box-bd">
                        <div class="unit size1of2">
                            <form enctype="multipart/form-data" method="post" action="/user/uploadsignature">
                                <div class="form-line">
                                    <label class="form-label unit size1of4"><?php echo $this->translate('Signature'); ?> :</label>
                                    <input type="hidden" name="user_id" value="<?php echo $this->user->getUserId() ?>">
                                    <?php echo Phoenix_View_Helper_Html::input(array('name' => 'file_signature', 'type' => 'file')) ?>
                                    <input type="submit" value="Envoyer" name="send_file">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <?php if($this->userCreationAllowed) { ?>
                <div class="line box">
                    <div class="box-hd">
                        <h2 class="box-title"><?php echo $this->translate('Mot de passe'); ?></h2>
                    </div>
                    <div class="box-bd">
                        <div class="unit size1of2">
                            <form enctype="multipart/form-data" method="post" action="/user/updatepassword">
                                <div class="form-line">
                                    <label class="form-label unit size1of4"><?php echo $this->translate('Mot de passe'); ?> :</label>
                                    <input type="hidden" name="user_id" value="<?php echo $this->user->getUserId() ?>">
                                    <?php echo Phoenix_View_Helper_Html::input(array('name' => 'user_password', 'type' => 'password')) ?>
                                    <input type="submit" value="Envoyer" name="update_password">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <?php } ?>
            </div>
            <div class="unit size1of2">
                <div class="line box">
                    <div class="box-hd">
                        <h2 class="box-title"><?php echo $this->translate('Visualisation de la signature'); ?></h2>
                    </div>
                    <div class="box-bd">
                        <div class="line unit size1of1">
                            <?php if ($this->showdeletesignature) { ?>
                                <?php echo $this->translate('Signature uploadée'); ?> : <a href="<?php echo $this->url(array('action' => 'deletesignature', 'controller' => 'user', 'module' => 'default', 'fileid' => $this->filesignatureid)) ?>" class="icon-list icon-delete"><?php echo $this->translate('supprimer'); ?></a>
                            <?php } else { ?>
                                <?php echo $this->translate('Signature par défaut'); ?> :
                            <?php } ?>
                        </div>
                        <br />
                        <div lass="line unit size1of1">
                            <?php echo $this->signature ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="line">
            <div class="unit size1of2">
                <div class="line box">
                    <div class="box-hd">
                        <h2 class="box-title"><?php echo $this->translate('Mes informations'); ?></h2>
                    </div>
                    <div class="box-bd">

                        <div class="line">
                            <label class="unit size1of3 form-label"><?php echo $this->translate('Nom'); ?> :</label>
                            <span class="unit size2of3"><?php echo $this->user->getNomPrenom() ?></span>
                        </div>
                        <div class="line">
                            <label class="unit size1of3 form-label"><?php echo $this->translate('Mail'); ?> :</label>
                            <span class="unit size2of3"><?php echo $this->user->getMail() ?></span>
                        </div>
                        <div class="line">
                            <label class="unit size1of3 form-label"><?php echo $this->translate('Télephone'); ?> :</label>
                            <span class="unit size2of3"><?php echo $this->user->getPhone() ?></span>
                        </div>
                        <div class="line">
                            <label class="unit size1of3 form-label"><?php echo $this->translate('Mobile'); ?> :</label>
                            <span class="unit size2of3"><?php echo $this->user->getMobile() ?></span>
                        </div>
                        <div class="line">
                            <label class="unit size1of3 form-label"><?php echo $this->translate('Groupe(s)'); ?> :</label>
                            <ul class="unit size2of3">
                            <?php foreach ($this->user->getGroups() as $aGroup) { ?>
                                <li><?php echo $aGroup['group_name'] ?></li>
                            <?php } ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="unit size1of2">
                <div class="line box">
                    <div class="box-hd">
                        <h2 class="box-title"><?php echo $this->translate('Changer la langue'); ?></h2>
                    </div>
                    <div class="box-bd">
                        <div class="unit size1of2">
                            <form enctype="multipart/form-data" method="post" action="/user/changelanguage">
                                <div class="form-line">
                                    <label class="form-label unit size1of4"><?php echo $this->translate('langue'); ?> :</label>
                                    <input type="hidden" name="user_id" value="<?php echo $this->user->getUserId() ?>">
                                    <select name="language" id ="user_language_select">
                                        <?php foreach ($this->selectListLanguages as $sKey => $sLanguage) { ?>
                                            <option value="<?php echo $sKey; ?>" <?php echo (trim($this->userLanguage) === $sKey) ? 'selected' : ''; ?>><?php echo $sLanguage; ?></option>
                                        <?php } ?>
                                    </select>
                                    <input type="submit" value="<?php echo $this->translate('Envoyer'); ?>" name="send_file" id="user_change_language">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
