<?php
$this->title = $this->translate('Nouveau devis');
$this->headTitle($this->title);
$this->headScript()->appendFile($this->baseUrl() . '/js/operation/new/index.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/operation/commonFeatures.js');
echo $this->FlashMessenger('error', 'popup');
?>
<div id="site-content">
    <div id="content-bd">
        <div class="form-section">
            <h1 class="page-title title-icon icon-doc"><?php echo $this->translate('Nouveau devis'); ?></h1>
        </div>
        <form action="<?php echo $this->url(array('action' => 'saveoperation', 'controller' => 'new', 'module' => 'operation')) ?>" method="post">
            <div class="line">
                <div class="unit size1of2">
                    <div class="box">
                        <div class="box-hd">
                            <h2 class="box-title">1. <?php echo $this->translate('Configuration de l\'opération'); ?></h2>
                        </div>
                        <div class="box-bd">
                            <div class="line">
                                <div class="unit size3of5">
                                    <div class="col">
                                        <div class="section">
                                            <div class="section-hd">
                                                <h2 class="section-title"><?php echo $this->translate('Intitulé de l\'opération'); ?></h2>
                                            </div>
                                            <div class="section-bd">
                                                <div class="line form-section">
                                                    <?php echo Phoenix_View_Helper_Html::input(array('name' => 'op_libelle', 'placeholder' => $this->translate('INTITULÉ DE L\'OPERATION'), 'class' => 'form-input input-big input-orange unit size1of1')); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="unit size2of5 lastUnit">
                                    <div class="col">
                                        <div class="section">
                                            <div class="section-hd">
                                                <h2 class="section-title"><?php echo $this->translate('Taux de conversion'); ?></h2>
                                            </div>
                                            <div class="section-bd">
                                                <div class="line form-section">
                                                    <?php echo Phoenix_View_Helper_Html::select(array('name' => 'op_taux_conversion', 'class' => 'form-select'), array('0 %' => array('value' => '0'), '25 %' => array('value' => '25'), '50 %' => array('value' => '50'), '75 %' => array('value' => '75'), '100 %' => array('value' => '100')), array('default_label' => $this->translate('choisir') . '...')); ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="section">
                                <div class="section-hd">
                                    <h2 class="section-title"><?php echo $this->translate('terminology_selection_label'); ?></h2>
                                </div>
                                <div class="section-bd">
                                    <div class="line form-line">
                                        <label class="unit size1of5 form-label" for="id_op_act_id"><?php echo $this->translate('operation_business_label'); ?> :</label>
                                        <div class="unit size3of5 date lastUnit">
                                            <?php echo My_View_Helper_Html::selectFromTable('r_custom_activites', array('name' => 'op_act_id', 'class' => 'unit size1of2 form-select'), array('value' => 'act_id', 'name' => 'act_libelle'), array('default_label' => $this->translate('choisir') . '...', 'clause_where' => 'actif = 1', 'clause_order' => 'ord ASC')) ?>
                                        </div>
                                    </div>
                                    <div class="line form-line">
                                        <label class="unit size1of5 form-label" for="id_op_type_id"><?php echo $this->translate('operation_category_label'); ?> :</label>
                                        <div class="unit size3of5 date lastUnit">
                                            <?php echo My_View_Helper_Html::selectFromTable('r_operation_type', array('name' => 'op_type_id', 'class' => 'unit size1of2 form-select'), array('value' => 'ot_id', 'name' => 'ot_libelle', 'class' => 'act_id'), array('default_label' => $this->translate('choisir') . '...', 'clause_where' => 'actif = 1', 'clause_order' => 'ord ASC')) ?>
                                        </div>
                                    </div>
                                    <div class="line form-line">
                                        <label class="unit size1of5 form-label" for="id_op_subtype_id"><?php echo $this->translate('operation_mecanic_label'); ?> :</label>
                                        <div class="unit size3of5 date lastUnit">
                                            <?php echo My_View_Helper_Html::selectFromTable('r_operation_type_sub', array('name' => 'op_subtype_id', 'class' => 'unit size1of2 form-select'), array('value' => 'ost_id', 'name' => 'ost_libelle', 'class' => 'ost_ot_id'), array('default_label' => $this->translate('choisir') . '...', 'clause_where' => 'actif = 1', 'clause_order' => 'ord ASC')) ?>
                                        </div>
                                    </div>
                                    <div class="line form-line">
                                        <label class="unit size1of5 form-label" for="id_operation_universe_id"><?php echo $this->translate('label_universe'); ?> :</label>
                                        <div class="unit size3of5 date lastUnit">
                                            <?php echo My_View_Helper_Html::selectFromTable('r_operation_universes', array('name' => 'operation_universe_id', 'class' => 'form-select unit size1of2', 'id' => 'id_operation_universe_id'), array('value' => 'r_operation_universe_id', 'name' => 'r_operation_universe_label'), array('default_label' => $this->translate('choisir') . '...', 'clause_where' => 'r_operation_universe_actif = 1', 'clause_order' => 'r_operation_universe_order ASC')) ?>
                                        </div>
                                    </div>
                                    <div class="line form-line">
                                        <label class="unit size1of5 form-label" for="id_operation_media_id"><?php echo $this->translate('label_participation_media'); ?> :</label>
                                        <div class="unit size3of5 date lastUnit">
                                            <?php echo My_View_Helper_Html::selectFromTable('r_operation_medias', array('name' => 'operation_media_id', 'class' => 'form-select unit size1of2', 'id' => 'id_operation_media_id'), array('value' => 'r_operation_media_id', 'name' => 'r_operation_media_label'), array('default_label' => $this->translate('choisir') . '...', 'clause_where' => 'r_operation_media_actif = 1', 'clause_order' => 'r_operation_media_order ASC')) ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="section">
                                <div class="section-hd">
                                    <h2 class="section-title"><?php echo $this->translate('Client'); ?></h2>
                                </div>
                                <div class="section-bd">
                                    <div class="form-section">
                                        <div class="line form-line">
                                            <label for="" class="form-label unit size1of3" for="id_autocomplete_client"><?php echo $this->translate('Choix du client'); ?> :</label>
                                            <div class="unit size1of3 gutter10">
                                                <?php echo Phoenix_View_Helper_Html::input(array('name' => 'op_cl_id', 'type' => 'hidden')) ?>
                                                <?php echo Phoenix_View_Helper_Html::input(array('name' => 'autocomplete_client', 'class' => 'form-input input-autocomplete size1of1')); ?>
                                            </div>
                                            <div class="unit size1of3 lastUnit">
                                                <a href="#" class="link-add" id="btn-client-add"><?php echo $this->translate('Créer un nouveau client'); ?></a>
                                            </div>
                                        </div>
                                        <!-- N'apparait que si un client est sélectionné -->
                                        <div class="line form-line" id="id_div_contact" style="<?php echo ($this->getParam('op_cl_id', null) != null ? '' : 'display:none') ?>">
                                            <label for="" class="form-label unit size1of3" for="id_op_ct_id"><?php echo $this->translate('Contact commercial'); ?> :</label>
                                            <div class="unit size1of3 gutter10">
                                                <?php echo Phoenix_View_Helper_Html::select(array('name' => 'op_ct_id', 'class' => 'form-select size1of1', 'value' => $this->getParam('op_ct_id'), 'default_option_label' => $this->translate('choisir') . '...'), array()); ?>
                                            </div>
                                            <div class="unit size1of3 lastUnit">
                                                <a href="#" class="link-add" id="btn-contact-add"><?php echo $this->translate('Créer un contact'); ?></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="section">
                                <div class="section-hd">
                                    <h2 class="section-title"><?php echo $this->translate('Dates'); ?></h2>
                                </div>
                                <div class="section-bd">
                                    <div class="form-section">
                                        <div class="line form-line">
                                            <label class="form-label unit size1of3" for="id_op_stamp_start"><?php echo $this->translate('Début gestion'); ?> :</label>
                                            <div class="unit size2of3 date lastUnit">
                                                <?php echo Phoenix_View_Helper_Html::input(array('name' => 'op_stamp_start', 'class' => 'date-input', 'placeholder' => $this->translate('JJ/MM/AAAA'), 'maxlenght' => '10')); ?>
                                            </div>
                                        </div>
                                        <?php if (Phoenix_Auth_User::getInstance()->isAllowed(AclFonctionnalites::CONSUMERING_DATES)) { ?>
                                        <div class="line form-line">
                                            <label class="form-label unit size1of3" for="id_op_dateConso_start"><?php echo $this->translate('Début conso'); ?> :</label>
                                            <div class="unit size2of3 date lastUnit">
                                                <?php echo Phoenix_View_Helper_Html::input(array('name' => 'op_dateConso_start', 'class' => 'date-input', 'placeholder' => $this->translate('JJ/MM/AAAA'), 'maxlenght' => '10')); ?>
                                            </div>
                                        </div>
                                        <div class="line form-line">
                                            <label class="form-label unit size1of3" for="id_op_dateConso_end"><?php echo $this->translate('Fin conso'); ?> :</label>
                                            <div class="unit size2of3 date lastUnit">
                                                <?php echo Phoenix_View_Helper_Html::input(array('name' => 'op_dateConso_end', 'class' => 'date-input', 'placeholder' => $this->translate('JJ/MM/AAAA'), 'maxlenght' => '10')); ?>
                                            </div>
                                        </div>
                                        <?php 
                                    }
                                    if (Phoenix_Auth_User::getInstance()->isAllowed(AclFonctionnalites::END_POSTE_DATE)) { ?>
                                        <div class="line form-line">
                                            <label class="form-label unit size1of3" for="id_op_datePoste_end"><?php echo $this->translate('Fin poste'); ?> :</label>
                                            <div class="unit size2of3 date lastUnit">
                                                <?php echo Phoenix_View_Helper_Html::input(array('name' => 'op_datePoste_end', 'class' => 'date-input', 'placeholder' => $this->translate('JJ/MM/AAAA'), 'maxlenght' => '10')); ?>
                                            </div>
                                        </div>
                                        <?php 
                                    }
                                    if (Phoenix_Auth_User::getInstance()->isAllowed(AclFonctionnalites::END_DATE)) { ?>
                                        <div class="line form-line">
                                            <label class="form-label unit size1of3" for="id_op_stamp_end"><?php echo $this->translate('Fin gestion'); ?> :</label>
                                            <div class="unit size2of3 date lastUnit">
                                                <?php echo Phoenix_View_Helper_Html::input(array('name' => 'op_stamp_end', 'class' => 'date-input', 'placeholder' => $this->translate('JJ/MM/AAAA'), 'maxlenght' => '10')); ?>
                                            </div>
                                        </div>
                                        <?php 
                                    }
                                    if (Phoenix_Auth_User::getInstance()->isAllowed(AclFonctionnalites::END_ARCHIVING_DATE)) { ?>
                                        <div class="line form-line">
                                            <label class="form-label unit size1of3" for="id_op_date_archivage_end"><?php echo $this->translate('Fin d\'archivage'); ?> :</label>
                                            <div class="unit size1of2 date">
                                                <?php echo Phoenix_View_Helper_Html::input(array('name' => 'op_date_archivage_end', 'class' => 'date-input', 'placeholder' => $this->translate('JJ/MM/AAAA'), 'maxlenght' => '10')); ?>
                                            </div>
                                        </div>
                                        <?php 
                                    } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="unit size1of2 lastUnit">
                    <div class="box">
                        <div class="box-hd">
                            <h2 class="box-title">2. <?php echo $this->translate('Choix des options'); ?></h2>
                        </div>
                        <div class="box-bd">
                            <?php
                            $iItemRanking = 1;
                            foreach ($this->activitiesKpis as $oActivityKpi) {
                                if ($oActivityKpi->countRelatedOperationOptionsPackages()) {
                                    $bIsFirstElementOfTheRow =  $iItemRanking & 1;
                                    if ($bIsFirstElementOfTheRow) {
                                        ?>
                                        <div class="line auto-show-option">
                                        <?php } ?>
                                        <div class="unit size1of2 <?php echo ($bIsFirstElementOfTheRow) ? 'gutter10' : 'lastUnit' ?>">
                                            <div class="section">
                                                <div class="section-hd">
                                                    <h2 class="section-title"><?php echo $oActivityKpi->getRActivityKpiLibelle() ?></h2>
                                                </div>
                                                <div class="section-bd">
                                                    <?php echo Phoenix_View_Helper_Html::retrieveOptionsListByActivityKpi($oActivityKpi); ?>
                                                </div>
                                            </div>
                                        </div>
                                        <?php if (!$bIsFirstElementOfTheRow) { ?>
                                        </div>
                                        <?php

                                    }
                                    ++$iItemRanking;
                                }
                            }
                            if ($this->countDetachedOperationOptions) {

                                $bIsFirstElementOfTheRow =  $iItemRanking & 1;
                                if ($bIsFirstElementOfTheRow) {
                                    ?>
                                    <div class="line auto-show-option">
                                    <?php } ?>
                                    <div class="unit size1of2 <?php echo ($bIsFirstElementOfTheRow) ? 'gutter10' : 'lastUnit' ?>">
                                        <div class="section">
                                            <div class="section-hd">
                                                <h2 class="section-title"><?php echo $this->translate('label_divers'); ?></h2>
                                            </div>
                                            <div class="section-bd">
                                                <?php echo Phoenix_View_Helper_Html::retrieveOptionsListByActivityKpi(); ?>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            <?php 
                        } ?>
                        </div>
                    </div>
                </div>
                <br/>
                <br/>
            </div>
            <div class="text-center">
                <a href="<?php echo $this->url(array('module' => 'operation', 'controller' => 'listing'), null, true) ?>" class="btn col"><?php echo $this->translate('Annuler'); ?></a><input type="submit" name="submit_ajout_operation" value="<?php echo $this->translate('Valider'); ?>" class="btn btn-orange" />
            </div>
        </form>
    </div>
</div>
