<form action="" method="get" id="id_form_add_new_reward">
    <?php echo Phoenix_View_Helper_Html::input(array('name' => 'op_id', 'type' => 'hidden', 'value' => $this->op_id)); ?>
    <div class="line form-line" >
        <div class="line form-line">
            <label class="unit size1of2 form-label" for=""><?php echo $this->translate('label_reward_name'); ?> :</label>
            <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'op_prime_libelle', 'class' => 'form-input unit size1of2 lastUnit')) ?>
        </div>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('label_reward_type'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::selectFromTable('r_reward_types', array('name' => 'operation_prime_r_reward_type_id', 'class' => 'form-select size1of2 unit lastUnit','required' => 'required'), array('value' => 'r_reward_type_id', 'name' => 'r_reward_type_label'), array('clause_where' => 'r_reward_type_actif = 1', 'default_label' => $this->translate('choisir') . '...')); ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('label_fix_amount'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('name' => 'operation_prime_fixed_amount', 'id' => 'id_operation_prime_fixed_amount_1', 'class' => 'form-input size1of2 unit lastUnit')) ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for="">%&nbsp;<?php echo $this->translate('label_product_amount'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('name' => 'operation_prime_product_price_pourcentage', 'id' => 'id_operation_prime_product_price_pourcentage_1', 'class' => 'form-input size1of2 unit lastUnit ')) ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('label_max_amount'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('name' => 'operation_prime_maximum_amount', 'id' => 'id_operation_prime_maximum_amount_1', 'class' => 'form-input size1of2 unit lastUnit')) ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('label_reward_currency'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::select(array('name' => 'operation_prime_currency_id', 'id' => 'id_operation_prime_currency_id_1', 'class' => 'form-select size1of2 unit lastUnit'), $this->rewardCurrenciesList, array('default_label' => $this->translate('choisir') . '...')); ?>
    </div>
    <div class="line form-line">
        <div class="unit size1of2">
            <?php echo $this->translate('label_reward_country'); ?> :
        </div>
        <div class="unit size1of2 lastUnit">
            <?php echo Phoenix_View_Helper_Html::checkbox(array('name' => 'select_all_reward_countries', 'class' => 'select_all_options', 'related_multiple_select_list_id' => 'operation_reward_countries_id', 'title' => $this->translate('select_all_deselect_all_label'), 'value' => 1)) ?>
            <br/>
            <?php
            echo Phoenix_View_Helper_Html::select(array('id' => 'operation_reward_countries_id', 'name' => 'operation_reward_countries[]', 'class' => 'unit size4of5 multiple-select-list-binded-to-checkbox', 'multiple' => 'multiple ', 'size' => 10, 'related-checkbox-id' => 'id_select_all_reward_countries'), $this->rewardCountriesList);
            ?>
        </div>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('label_expedition_mode'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::selectFromTable('r_reward_expedition_modes', array('name' => 'operation_prime_r_reward_expedition_mode_id', 'id' => 'id_operation_prime_r_reward_expedition_mode_id_1', 'expedition-mode-transporter-id' => \RRewardExpeditionModes::R_REWARD_EXPEDITON_MODE_TRANSPORTER_ID, 'class' => 'form-select size1of2 unit lastUnit'), array('value' => 'r_reward_expedition_mode_id', 'name' => 'r_reward_expedition_mode_label'), array('clause_where' => 'r_reward_expedition_mode_actif = 1', 'default_label' => $this->translate('choisir') . '...')); ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('label_transporter'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::selectFromTable('r_reward_transporters', array('id' => 'id_operation_prime_r_reward_transporter_id_1', 'name' => 'operation_prime_r_reward_transporter_id', 'class' => 'form-select size1of2 unit lastUnit'), array('value' => 'r_reward_transporter_id', 'name' => 'r_reward_transporter_label'), array('clause_where' => 'r_reward_transporter_actif = 1', 'default_label' => $this->translate('choisir') . '...')); ?>
    </div>
    <div class="text-center">
        <input type="hidden" name="submit_new_operation_reward" value="1" />
        <input type="submit" value="<?php echo $this->translate('Valider'); ?>" class="btn btn-orange">
    </div>
</form>