<form method="post" id="id_form_operation_reward_countries">
    <div class="form-section mini_list_checkbox_popup_form_container">
        <table class="list list-main">
            <thead>
                <tr>
                    <th width="40" class="check-column"><input id="check_all_reward_related_data" type="checkbox" /></th>
                    <th><span class="notsortable"><?php echo $this->translate('Nom'); ?></span></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->rewardCountriesList as $aCountry): ?>
                    <tr class="tr-check <?php echo $this->cycle(array('', 'alt'))->next() ?>">
                        <td class="check-column">
                            <input class="reward_related_data" type="checkbox" name="operation_reward_countries[]" value="<?php echo $aCountry['r_country_id'] ?>" <?php echo ($aCountry['is_selected'] == 1 ? 'checked="checked"' : '') ?>>
                        </td>
                        <td><?php echo $aCountry['r_country_name'] ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="text-center">
        <input type="hidden" name="operation_reward_id" value="<?php echo $this->operationRewardId ?>" />
        <input type="hidden" name="submit_operation_reward_countries" value="1" />
        <input type="submit" value="<?php echo $this->translate('Valider'); ?>" class="btn btn-orange" />
    </div>
</form>


