Dans la cadre de l'élaboration d'un devis, vous avez demandé la création du compte client <?php echo $this->client_name ?>.
Pour finaliser cette étape, vous devez compléter plusieurs informations obligatoires pour le bon déroulement des opérations gérées pour ce compte.
Merci de vous rendre sur la fiche client afin de finaliser la qualification du compte :
<br>
<a href="<?php echo $this->url ?>">Lien vers la fiche client du compte</a>