Bonjour,

Le compte client <?php echo $this->cl_libelle; ?> dispose d'un dispositif de facturation localisé à l'étranger (Pays : <?php echo $this->country_name; ?>). Dans ce cadre, il est important de contrôler les taux de TVA applicables et les mentions spécifiques à indiquer sur les documents pour facturer dans les règles de l'art.

Merci de vous rapprocher du Directeur de Clientèle, de la DAF et de la Direction des Opérations Clients pour bien coordonner la facturation.

Merci d'avance.