<!-- DIALOG / AJOUT / MODIFICATION -->
<form id="id_form_update_rscenario" action="<?php echo $this->url(array('module' => 'administration', 'controller' => 'rscenario', 'action' => 'update')) ?>" method="post">
    <input type="hidden" name="submit_update_rscenario" value="1">
    <input type="hidden" name="r_scenario_id" value="<?php echo $this->r_scenario_id; ?>">

    <div class="line form-line">
        <label class="unit size1of3 form-label" for='id_r_scenario_libelle'><?php echo $this->translate('Libellé');?> :</label>
		<?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'r_scenario_libelle', 'value' => $this->r_scenario_libelle, 'class' => 'unit size2of3 form-input lastUnit')) ?>
    </div>
	
    <div class="line form-line">
        <label class="unit size1of3 form-label" for='id_r_scenario_libelle_en'><?php echo $this->translate('Libellé (anglais)');?>:</label>
		<?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'r_scenario_libelle_en', 'value' => $this->r_scenario_libelle_en, 'class' => 'unit size2of3 form-input lastUnit')) ?>
    </div>
	
	<div class="line form-line">
		<label class="unit size1of3 form-label" for='id_r_scenario_actif'><?php echo $this->translate('Scénario actif');?></label>
		<?php echo Phoenix_View_Helper_Html::checkbox(array('name' => 'r_scenario_actif', 'value' => 1, 'default_value' => $this->r_scenario_actif)) ?>
	</div>
	
    <div class="text-center">
        <input type="submit" value="<?php echo $this->translate('Valider'); ?>" class="btn btn-orange">
    </div>
</form>


<script language="javascript">
    $(document).ready(function() {
        $('#id_form_update_rscenario').ajaxForm({
            divId:'id_dialog_update_rscenario'
        });
    });
</script>
