<form action="" method="get" id="id_form_edition">
    <input type="hidden" name="fact_id" value="<?php echo $this->getParam('fact_id') ?>" />
    <input type="hidden" name="cl_id" value="<?php echo $this->getParam('cl_id') ?>" />
    <input type="hidden" name="op_id" value="<?php echo $this->getParam('op_id') ?>" />
    <div class="line form-line" >
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('Facture'); ?> :</label>
        <?php echo $this->fact_reference ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('Nom du contact de facturation'); ?> :</label>
        <!-- //32655 MAJ de la syntaxe de concaténation nom prénom pour MySQL-->
        <?php echo Phoenix_View_Helper_Html::selectFromTable('contacts', array('name' => 'ct_id', 'value' => $this->ct_id, 'class' => 'form-select unit size1of2 lastUnit'), array('name' => "CONCAT(COALESCE(ct_firstname, ''),' ',COALESCE(ct_lastname, ''))", 'value' => 'ct_id'), array('clause_where' => "cl_id='" . $this->getParam('cl_id') . "'")); ?>
        <input type="hidden" name="fact_attention" value="<?php echo $this->fact_attention ?>">
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('Adresse  1 du site à facturer'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'fact_adresse1', 'value' => $this->fact_adresse1)) ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('Adresse  2 du site à facturer'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'fact_adresse2', 'value' => $this->fact_adresse2)) ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('Adresse  3 du site à facturer'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'fact_adresse3', 'value' => $this->fact_adresse3)) ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('Code postal du site à facturer'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'fact_code_postal', 'value' => $this->fact_code_postal)) ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('Ville du site à facturer'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'fact_ville', 'value' => $this->fact_ville)) ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for=""><?php echo $this->translate('Pays du site à facturer'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'fact_pays', 'value' => $this->fact_pays)) ?>
    </div>
    <div class="line form-line">
        <label class="form-label" for=""><?php echo $this->translate('Mentions spécifiques à ajouter sur la facture'); ?> :</label>
    </div>
    <div class="line form-section">
        <?php echo Phoenix_View_Helper_Html::textarea(array('name' => 'fact_mention_spec', 'value' => $this->fact_mention_spec, 'cols' => 60, 'rows' => 4, 'class' => 'form-textarea unit size1of1 lastUni')); ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of2 form-label" for="id_send_mail"><?php echo $this->translate('Envoi de la facture par mail'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::checkbox(array('name' => 'send_mail'), array('checked' => $this->bAutoCheckSendEmail)) ?>
    </div>
    <div id="mail_container" class="line form-section<?php if (!$this->bAutoCheckSendEmail) { ?> ui-helper-hidden <?php } ?>">
        <div class="line form-line">
            <span class="unit size1of4 form-label"><?php echo $this->translate('à'); ?> : </span>
            <?php echo Phoenix_View_Helper_Html::input(array('name' => 'mail_dest[to]', 'type' => 'text', 'value' => $this->mail_dest_to, 'placeholder' => $this->translate('Indiquez ici une ou plusieurs adresses, séparées par une virgule'), 'class' => 'unit size3of4 form-input')); ?>
        </div>

        <div class="line form-line">
            <span class="unit size1of4 form-label"><?php echo $this->translate('copie'); ?> : </span>
            <?php echo Phoenix_View_Helper_Html::input(array('name' => 'mail_dest[cc]', 'type' => 'text', 'value' => $this->mail_dest_cc, 'placeholder' => $this->translate('Indiquez ici une ou plusieurs adresses, séparées par une virgule'), 'class' => 'unit size3of4 form-input')); ?>
        </div>

        <div class="line form-line">
            <span class="unit size1of4 form-label"><?php echo $this->translate('copie cachée'); ?> : </span>
            <?php echo Phoenix_View_Helper_Html::input(array('name' => 'mail_dest[bcc]', 'type' => 'text', 'value' => $this->mail_dest_bcc, 'placeholder' => $this->translate('Indiquez ici une ou plusieurs adresses, séparées par une virgule'), 'class' => 'unit size3of4 form-input')); ?>
        </div>

        <div class="line form-line">
            <span class="unit size1of4 form-label"><?php echo $this->translate('Sujet du mail'); ?> : </span>
            <?php echo Phoenix_View_Helper_Html::input(array('name' => 'mail_subject', 'type' => 'text', 'value' => $this->mail_subject, 'placeholder' => $this->translate('Indiquez ici le sujet du mail'), 'class' => 'unit size3of4 form-input')); ?>
        </div>

        <div class="line form-section">
            <textarea name="mail_content" id="id_mail_content" rows="40" cols="100%" class="form-textarea unit size1of1 lastUnit"><?php echo $this->mail_content; ?></textarea>
        </div>
    </div>

    <div class="text-center">
        <input type="submit" value="<?php echo $this->translate('Valider'); ?>" class="btn btn-orange">
        <input type="button" value="<?php echo $this->translate('Annuler'); ?>" id="id_btn_annuler" class="btn btn-orange">
    </div>
</form>


<script language="javascript">
    $(document).ready(function () {

        $('#id_ct_id').change(function () {
            AjaxComponent.ajaxDiv('/comptabilite/factures/edition/view_site/1/op_id/', $('#id_form_edition').serialize(), 'id_popup_edition');
        })

        $('#id_send_mail').change(function () {
            $('#mail_container').toggle();
        })

        $('#id_form_edition').ajaxForm({action: '/comptabilite/factures/edition/submit/1', divId: 'id_popup_edition',
            before:function(){
				$('#id_mail_content').val(CKEDITOR.instances.id_mail_content.getData());
            },
            success: function () {
                $("#id_popup_edition").dialog({close: function () {
                    Component.refreshPage()
                }})
            }
        });

        $('#id_btn_annuler').click(function () {
            $('#id_popup_edition').dialog('close');
        });

        CKEDITOR.replace('id_mail_content',
			{	
			toolbar: [
				[ 'Bold', 'Italic', '-', 'NumberedList', 'BulletedList', '-', 'Link', 'Unlink' ],
				[ 'FontSize', 'TextColor', 'BGColor' ]
			]}
		);

    });
</script>