<?php
$this->title = $this->translate('Listing des axes');
$this->headTitle($this->title);
echo $this->FlashMessenger('error');

echo $this->FlashMessenger('default');
$this->headScript()->appendFile($this->baseUrl() . '/js/administration/axes/index.js');
?>

<div id="actions-bar" class="actions-bar-indicators">
    <div class="unit size1of5">
        <h1 class="page-title"><?php echo $this->title; ?></h1>
    </div>

    <div class="unit size2of5">
        <form method="get" id="axes_selection_form" action ="<?php echo $this->url(array('module' => 'administration', 'controller' => 'axes', 'action' => 'index'), null, true) ?>" >
            <div class="line">
                <div class="unit size1of1 gutter10">
                    <div class="section">
                        <div class="section-hd">
                            <h2 class="section-title"><?php echo $this->translate('Axes'); ?></h2>
                        </div>
                        <div class="section-bd">
                            <div class="line form-line align-fields-inblock">
                                <label class="unit size1of2 form-label" for="id_find_axe_id"> <?php echo $this->translate('Nom de l\'axe'); ?> :</label>
                                <?php echo Phoenix_View_Helper_Html::select(array('name' => 'find_axe_id', 'class' => 'form-select unit size1of2'), $this->aAxesNames, array('default_label' => $this->translate('Choisir') . '...')) ?>
                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                        <input type="submit" name="findbyfields" value="<?php echo $this->translate('Afficher') ?>" class="btn btn-orange">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div id="site-content" style = "clear: both">
    <div class="content-list">
        <?php if (isset($this->oPaginator)) { ?>
            <div class="list-actions">
                <div class="unit size1of5">
                    <input href="#new" id="btn_new" title="<?php echo $this->translate('Création d\'une nouvelle section') ?>" type="button" class="btn btn-orange btn-big" axe_table_name='<?php echo $this->sAxeTableName ?>' value="<?php echo $this->translate('Nouvelle section'); ?>" />
                </div>
                <div class="unit rightUnit">
                    <div class="unit">
                        <?php echo $this->paginationControl($this->oPaginator, 'Sliding', '/partials/pagination.phtml'); ?>
                    </div>
                </div>
            </div>
            <table class="list list-main">
                <thead>
                    <tr>
                        <?php foreach ($this->aHeader as $sKey => $sElement) { ?>
                            <th><?php echo My_View_Helper_Html::UrlOrderBy($sKey, $sElement); ?></th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->oPaginator as $aAxeDatas) {
                        ?>
                        <tr class="<?php echo $this->cycle(array('', 'alt'))->next() ?>">
                            <?php
                            $iColumnCounter = 0;
                            foreach ($aAxeDatas as $aAxeDataElement) {
                                ?>
                                <td>
                                    <?php if (0 === $iColumnCounter) { ?>
                                        <a href="#delete" axe_identifier='<?php echo $this->getParam('find_axe_id') ?>' axe_table_name='<?php echo $this->sAxeTableName ?>' axe_id='<?php echo $aAxeDataElement ?>' confirmation_message="<?php echo $this->translate("Confirmez-vous la suppression de la section") ?>" class="icon-list icon-delete" title="<?php echo $this->translate('Supprimer la section'); ?>"></a>
                                        <a href="#edit" axe_table_name='<?php echo $this->sAxeTableName ?>' axe_id='<?php echo $aAxeDataElement ?>' class="icon-list icon-edit" title="<?php echo $this->translate('Modifier la section N°') . ' ' . $aAxeDataElement; ?>"></a>
                                        <?php
                                        ++$iColumnCounter;
                                    }
                                    ?>
                                    <?php echo $aAxeDataElement; ?>
                                </td>
                            <?php } ?>
                        <tr/>
                    <?php } ?>
                </tbody>
            </table>
        <?php } ?>
    </div>
</div>

<script language="javascript">
    $(document).ready(function () {
        $('#axes_selection_form').submit(function () {
            return prevalidate('<ul><li><?php echo addslashes($this->translate('Merci de préciser le nom de l\'axe avant d\'afficher le résultat')) ?></li></ul>');
        });
    });
</script>