<div class="footer-cs-website"><?php echo $this->getSettingValue(Settings::SETTING_KEY_COMPANY_WEBSITE)?></div>
<div class="footer-content">
    <?php echo $this->getSettingValue(Settings::SETTING_KEY_COMPANY_NAME) ?> - <?php echo $this->getSettingValue(Settings::SETTING_KEY_COMPANY_STATUTES) ?> <br/>
    <?php echo $this->getSettingValue(Settings::SETTING_KEY_COMPANY_ADDRESS)?> – Tel : <?php echo $this->getSettingValue(Settings::SETTING_KEY_COMPANY_PHONE_NUMBER)?> – Fax : <?php echo $this->getSettingValue(Settings::SETTING_KEY_COMPANY_FAX_NUMBER)?> - e-mail : <?php echo $this->getSettingValue(Settings::SETTING_KEY_EMAIL_CONTACT)?>
</div>