<?php 
    if(!is_numeric($this->sData)){
        throw new \LogicException('Variable sData expects a numeric value , "'.(is_object($this->sData)?get_class($this->sData):gettype($this->sData)).'" defined');
    }
?>
<div class="simple-data-block <?php echo ($this->bLastElement) ? 'simple-data-bloc-with-no-margin-right' : '' ?>">
    <div class="simple-data-block-title">
        <span><?php echo $this->sKpiTitle ?></span>
    </div>
    <div class="simple-data-block-content">
        <div class="content-block-number"><?php echo Phoenix_Data_Convert::formatNumber($this->sData, false, false); ?>%</div>
        <div class="simple-pourcentage-progress-bar">
            <div class="simple-pourcentage-block-center">
                <div class="simple-pourcentage-block-percent">
                    <span class="bar-percent"></span>
                    <span class="bar-progress" style="width: <?php echo ((float) $this->sData > 100) ? 100 : $this->sData; ?>%"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="content-block-legend"><?php echo $this->sKpiLegend; ?></div>
</div>