<form method="post"  id="id_form_template_cultures">
    <div class="form-section mini_list_checkbox_popup_form_container">
        <table class="list list-main">
            <thead>
                <tr>
                    <th width="40" class="check-column"><input id="check_all_template_related_data" type="checkbox" /></th>
                    <th><span class="notsortable"><?php echo $this->translate('Nom'); ?></span></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->cultures as $aCulture): ?>
                    <tr class="tr-check <?php echo $this->cycle(array('', 'alt'))->next() ?>">
                        <td class="check-column">
                            <input class="template_related_data" type="checkbox" name="templatecultures[]" value="<?php echo $aCulture['r_culture_id'] ?>" <?php echo ($aCulture['is_selected'] == 1 ? 'checked="checked"' : '') ?>>
                        </td>
                        <td><?php echo $aCulture['r_culture_label'] ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="text-center">
        <input type="hidden" name="template_id" value="<?php echo $this->templateId ?>" />
        <input type="hidden" name="submit_template_cultures" value="1" />
        <input type="submit" value="<?php echo $this->translate('Valider'); ?>" class="btn btn-orange" />
    </div>
</form>


