<table class="list list-simple">
    <tbody>
        <tr>
            <th><span class="notsortable"><?php echo $this->translate('label_cultures'); ?></span></th>
        </tr>
        <?php
        foreach ($this->templateCultures as $oCulture):
            ?>
            <tr class="">
                <td><?php echo $oCulture->getRCultureLabel() ?></td>
            </tr>
        <?php endforeach; ?>

    </tbody>
</table>