<table class="list">
    <thead>
        <tr>
            <th width="15" class="column-noborder"></th>
            <th width=""><span class="notsortable"><?php echo $this->translate('Libellé'); ?></span></th>
            <th width="8%"><span class="notsortable"><?php echo $this->translate('Actif'); ?></span></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->metiers as $metier) { ?>
            <tr class="class_form_activite" action="<?php echo $this->url(array('module' => 'administration', 'controller' => 'rtypesdevis', 'action' => 'updateactivite')) ?>" model_name="RCustomActivites" primary_value="<?php echo $metier->getActId(); ?>">
                <td width="15"></td>
                <td><?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'id' => 'id_act_libelle_' . $metier->getActId(), 'name' => 'act_libelle', 'class' => 'form-input input-editable size1of1', 'value' => $metier->getActLibelle())) ?></td>
                <td><?php echo Phoenix_View_Helper_Html::checkbox(array('name' => 'actif', 'id' => 'id_actif_' . $metier->getActId(), 'value' => 1, 'class' => 'form-input input-editable size1of1', 'default_value' => $metier->getActif())) ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<div class="section">
    <div class="section-hd">
        <h2 class="section-title"><?php echo $this->translate('Ajouter un nouveau métier'); ?></h2>
    </div>

    <div class="section-bd">
        <form id="id_form_new_activites" action="<?php echo $this->url(array('module' => 'administration', 'controller' => 'rtypesdevis', 'action' => 'manageactivites')) ?>" method="post">
            <input type="hidden" name="submit_new_activite" value="1">

            <div class="line form-line">
                <label class="unit size1of3 form-label" for='id_act_libelle'><?php echo $this->translate('Libellé'); ?> :</label>
                <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'act_libelle', 'value' => '', 'class' => 'unit size2of3 form-input lastUnit')) ?>
            </div>

            <div class="text-center">
                <input type="submit" value="<?php echo $this->translate('Ajouter'); ?>" class="btn btn-orange">
            </div>
        </form>
    </div>
</div>

<script language="javascript">
    $(document).ready(function() {
        $('.class_form_activite').formUpdate({});

        $('#id_form_new_activites').ajaxForm({
            divId: 'id_dialog_manage_activites'
        });
    });
</script>