<table class="list">
    <thead>
        <tr>
            <th width="15" class="column-noborder"></th>
            <th width=""><span class="notsortable"><?php echo $this->translate('Libellé'); ?></span></th>
            <th width="8%"><span class="notsortable"><?php echo $this->translate('Actif'); ?></span></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->subtypes as $subtype) { ?>
            <tr class="class_form_subtype" action="<?php echo $this->url(array('module' => 'administration', 'controller' => 'rtypesdevis', 'action' => 'updatesubtype')) ?>" model_name="ROperationTypeSub" primary_value="<?php echo $subtype->getOstId(); ?>">
                <td width="15"></td>
                <td><?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'id' => 'id_ost_libelle_' . $subtype->getOstId(), 'name' => 'ost_libelle', 'class' => 'form-input input-editable size1of1', 'value' => $subtype->getOstLibelle())) ?></td>
                <td><?php echo Phoenix_View_Helper_Html::checkbox(array('name' => 'actif', 'id' => 'id_actif_' . $subtype->getOstId(), 'value' => 1, 'class' => 'form-input input-editable size1of1', 'default_value' => $subtype->getActif())) ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<div class="section">
    <div class="section-hd">
        <h2 class="section-title"><?php echo $this->translate('Ajouter une nouvelle mécanique'); ?></h2>
    </div>

    <div class="section-bd">
        <form id="id_form_new_subtypes" action="<?php echo $this->url(array('module' => 'administration', 'controller' => 'rtypesdevis', 'action' => 'managesubtypes')) ?>" method="post">
            <input type="hidden" name="submit_new_subtype" value="1">
            <input type="hidden" name="ot_id" value="<?php echo $this->ot_id; ?>">

            <div class="line form-line">
                <label class="unit size1of3 form-label" for='id_ost_libelle'><?php echo $this->translate('Libellé'); ?> :</label>
                <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'ost_libelle', 'value' => '', 'class' => 'unit size2of3 form-input lastUnit')) ?>
            </div>

            <div class="text-center">
                <input type="submit" value="<?php echo $this->translate('Ajouter'); ?>" class="btn btn-orange">
            </div>
        </form>
    </div>
</div>

<script language="javascript">
    $(document).ready(function() {
        $('.class_form_subtype').formUpdate({});

        $('#id_form_new_subtypes').ajaxForm({
            divId: 'id_dialog_manage_subtypes'
        });
    });
</script>