<?php
$this->title = $this->translate('title_adminstration_r_cultures_listing');
$this->headTitle($this->title);

$this->headScript()->appendFile($this->baseUrl() . '/js/administration/rcultures/RCultureManager.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/administration/rcultures/index.js');
$bCreateEditIsAllowed = Phoenix_Auth_User::mvcActionIsAllowed('administration','rcultures','loadrcultureeditionpopup')  && Phoenix_Auth_User::mvcActionIsAllowed('administration','rcultures','saverculturedata');
$bDeleteIsAllowed = Phoenix_Auth_User::mvcActionIsAllowed('administration','rcultures','deleterculturerecord');
?>

<div id="actions-bar">
    <div class="unit size1of5">
        <h1 class="page-title"><?php echo $this->title; ?></h1>
        <?php if($bCreateEditIsAllowed){ ?>
        <input href="#" id="btn-add-new-culture" type="button" data-culture-popup-title="<?php echo $this->translate('title_culture_addition_popup_title') ?>" class="btn btn-orange btn-big" value="<?php echo $this->translate('label_button_add_new_culture_label'); ?>" />
        <?php } ?>
    </div>
    <div class="unit size3of5">
        <div class="search">
            <form method="get" id="cultures-form" action ="<?php echo $this->url(array('module' => 'administration', 'controller' => 'rcultures', 'action' => 'index'), null, true) ?>" >
                <input type="text" name="findword" class="form-input" value="<?php echo isset($this->findword) ? $this->findword : ''; ?>" placeholder="<?php echo $this->translate('placeholder_search'); ?>" autocomplete="off" />
                <input type="submit" value="<?php echo $this->translate('OK'); ?>" class="btn btn-orange" />
                <input type="button" value="<?php echo $this->translate('label_advanced_search'); ?>" class="btn btn-big btn-adsearch" id="btn-adsearch" />
            </form>
        </div>
    </div>
</div>
<div id="site-content">
    <div class="content-list">
        <div class="list-actions">
            <div class="unit col">
                <a class="icon icon-32 icon-excel" href="<?php echo $this->url(array('format' => 'csv'), null, false) . '?' . $_SERVER['QUERY_STRING'] ?>" title="<?php echo $this->translate('label_export_excel'); ?>"><?php echo $this->translate('label_export_excel'); ?></a>
            </div>
            <div class="unit rightUnit">
                <div class="unit col">
                    <?php echo $this->NotifySearch()->link() ?>
                </div>
                <div class="unit">
                    <?php echo $this->paginationControl($this->paginator, 'Sliding', '/partials/pagination.phtml'); ?>
                </div>
            </div>
        </div>
        <table class="list list-main">
            <thead>
                <tr>
                    <th width="26" class="column-noborder"></th>
                    <th width="26" class="column-noborder"></th>
                    <th>
                        <?php echo My_View_Helper_Html::UrlOrderBy('r_culture_id', $this->translate('label_id')); ?>
                    </th>
                    <th>
                        <?php echo My_View_Helper_Html::UrlOrderBy('r_culture_code', $this->translate('label_culture_code')); ?>
                    </th>
                    <th>
                        <?php echo My_View_Helper_Html::UrlOrderBy('r_culture_label', $this->translate('label_culture_label')); ?>
                    </th>
                    <th>
                        <?php echo My_View_Helper_Html::UrlOrderBy('r_lang_libelle', $this->translate('label_language_culture')); ?>
                    </th>
                    <th>
                        <?php echo My_View_Helper_Html::UrlOrderBy('r_culture_actif', $this->translate('label_actif')); ?>
                    </th>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $aCulture): ?>
                    <tr class="<?php echo $this->cycle(array('', 'alt'))->next() ?>">
                        <td>
                            <?php if($bDeleteIsAllowed){ ?>
                            <a href="#delete" class="icon-list icon-delete" data-culture-id="<?php echo $aCulture['r_culture_id']; ?>" delete-culture-record-confirmation-message="<?php echo $this->translate('text_confirm_culture_record_deletion') . ' : ' . $aCulture['r_culture_label'] ?>" title="<?php echo $this->translate('label_link_delete_culture'); ?>"><?php echo $this->translate('label_link_delete_culture'); ?></a>
                            <?php } ?>
                        </td>
                        <td>
                            <?php if($bCreateEditIsAllowed){ ?>
                            <a href="#edit" class="icon-list icon-edit" data-culture-popup-title="<?php echo $this->translate('title_edition'); ?>" data-culture-id="<?php echo $aCulture['r_culture_id']; ?>" title="<?php echo $this->translate('label_link_edit_culture'); ?>"><?php echo $this->translate('label_link_edit_culture'); ?></a>
                            <?php } ?>
                        </td>
                        <td align="left"><?php echo $aCulture['r_culture_id']; ?></td>
                        <td align="left"><?php echo $aCulture['r_culture_code']; ?></td>
                        <td align="left"><?php echo $aCulture['r_culture_label']; ?></td>
                        <td align="left"><?php echo $aCulture['r_lang_libelle']; ?></td>
                        <td align="left"><?php echo $aCulture['r_culture_actif']; ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<div id="id-dialog-search" title="<?php echo $this->translate('label_advanced_search'); ?>" style="display:none;">
    <form action="<?php echo $this->BaseUrl() ?>/administration/rcultures/index" method="GET">
        <div class="section-bd">
            <div class="line form-line">
                <label class="unit size1of2 form-label" for="id-r-culture-id"><?php echo $this->translate('label_id'); ?> :</label>
                <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'find_r_culture_id', 'class' => 'unit size1of2 form-input lastUnit')) ?>
            </div>

            <div class="line form-line">
                <label class="unit size1of2 form-label" for="id-r-culture-code"><?php echo $this->translate('label_culture_code'); ?> :</label>
                <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'find_r_culture_code', 'class' => 'unit size1of2 form-input lastUnit')) ?>
            </div>

            <div class="line form-line">
                <label class="unit size1of2 form-label" for="id-r-culture-label"><?php echo $this->translate('label_culture_label'); ?> :</label>
                <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'name' => 'find_r_culture_label', 'class' => 'unit size1of2 form-input lastUnit')) ?>
            </div>
            <div class="line form-line">
                <label class="unit size1of2 form-label" for='id-r-culture-language-code'><?php echo $this->translate('label_language_culture'); ?> :</label>
                <?php
                echo Phoenix_View_Helper_Html::selectFromTable(
                        'r_languages', array('name' => 'find_r_culture_language_code', 'class' => 'unit size1of2 form-select lastUnit', 'id' => 'id-r-culture-language-code'), array('name' => 'r_lang_libelle', 'value' => 'r_lang_code'), array('default_label' => $this->translate('choisir') . '...')
                );
                ?>
            </div>
            <div class="line form-line">
                <label class="unit size1of2 form-label" for="id-r-culture-actif"><?php echo $this->translate('label_actif'); ?> :</label>
                <?php echo Phoenix_View_Helper_Html::checkbox(array('name' => 'find_r_culture_actif', 'value' => 1, 'id' => 'id-r-culture-actif')); ?>
            </div>
        </div>
        <div class="text-center">
            <input type="submit" name="findbyfields" value="<?php echo $this->translate('label_search'); ?>" class="btn btn-orange">
        </div>
    </form>
</div>
