<form id="culture-update-form" action="<?php echo $this->url(array('module' => 'administration', 'controller' => 'rcultures', 'action' => 'saverculturedata')) ?>" method="post">
    <?php echo Phoenix_View_Helper_Html::input(array('type' => 'hidden', 'name' => 'r_culture_id', 'value' => isset($this->rCulture) ? $this->rCulture->getRCultureId() : '')) ?>
    <div class="line form-line">
        <label class="unit size1of3 form-label" for='id-r-culture-code'><?php echo $this->translate('label_culture_code'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'id' => 'id-r-culture-code', 'name' => 'r_culture_code', 'class' => 'unit size2of3 form-input lastUnit', 'value' => isset($this->rCulture) ? $this->rCulture->getRCultureCode() : '')) ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of3 form-label" for='id-r-culture-label'><?php echo $this->translate('label_culture_label'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::input(array('type' => 'text', 'id' => 'id-r-culture-label', 'name' => 'r_culture_label', 'class' => 'unit size2of3 form-input lastUnit', 'value' => isset($this->rCulture) ? $this->rCulture->getRCultureLabel() : '')) ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of3 form-label" for='id-r-culture-language-code'><?php echo $this->translate('label_language_culture'); ?> :</label>
        <?php
        echo Phoenix_View_Helper_Html::selectFromTable(
                'r_languages', array('name' => 'r_culture_language_code', 'class' => 'unit size1of2 form-select lastUnit', 'value' => isset($this->rCulture) ? $this->rCulture->getRCultureLanguageCode() : '', 'id' => 'id-r-culture-language-code'), array('name' => 'r_lang_libelle', 'value' => 'r_lang_code'), array('default_label' => $this->translate('choisir') . '...')
        );
        ?>
    </div>
    <div class="line form-line">
        <label class="unit size1of3 form-label" for='id-r-culture-actif'><?php echo $this->translate('label_actif'); ?> :</label>
        <?php echo Phoenix_View_Helper_Html::checkbox(array('id' => 'id-r-culture-actif', 'name' => 'r_culture_actif', 'value' => 1, 'default_value' => isset($this->rCulture) ? $this->rCulture->getRCultureActif() : '')) ?>
    </div>
    <div class="text-center">
        <input type="submit" value="<?php echo $this->translate('Valider'); ?>" class="btn btn-orange">
    </div>
</form>
