<?php
$this->title = $this->translate('Contacts');
$this->headTitle($this->title);
?>
<?php echo $this->partial('partials/actionsbar.phtml', array('cl_id' => $this->cl_id, 'cl_libelle' => $this->cl_libelle)); ?>
<div id="site-content">
    <?php echo $this->partial('partials/menu.phtml', array('cl_id' => $this->cl_id)); ?>
    <div id="content-bd">
        <div class="list-actions">
            <div class="unit col">
                <a class="icon icon-32 icon-excel" href="<?php echo $this->url(array('format' => 'csv'), null, false) . '?' . $_SERVER['QUERY_STRING'] ?>" title="<?php echo $this->translate('Exporter au format Excel'); ?>"><?php echo $this->translate('Exporter au format Excel'); ?></a>
            </div>
            <div class="unit size1of5">
                <input type="button" class="btn btn-orange btn-big" id="id_btn_ajout_contact" value="<?php echo $this->translate('Nouveau contact'); ?>" />
            </div>
            <div class="unit">
                <div class="search">
                    <form action="<?php echo $this->BaseUrl() ?>/client/contact/client" method="get">
                        <input type="text" name="findword" class="form-input" value="<?php if (isset($_REQUEST["findword"])) echo $_REQUEST["findword"]; ?>" placeholder="<?php $this->translate('Rechercher'); ?>" autocomplete="off" />
                        <input type="submit" value="OK" class="btn btn-orange" />
                        <input type="button" value="<?php echo $this->translate('Recherche avancée'); ?>" class="btn btn-big btn-adsearch" id="btn_adsearch" />
                        <input type="hidden" name="cl_id" value="<?php echo $this->cl_id; ?>" />
                    </form>
                </div>
            </div>
            <div class="unit rightUnit">
                <div class="unit col">
                    <?php echo $this->NotifySearch()->link(array('cl_id' => $this->cl_id)) ?>
                </div>
                <div class="unit">
                    <?php echo $this->paginationControl($this->paginator, 'Sliding', '/partials/pagination.phtml'); ?>
                </div>
            </div>
        </div>
        <table class="list list-main">
            <thead>
                <tr>
                    <th width="26" class="column-noborder"></th>
                    <th width="26" class="column-noborder"></th>
                    <th width="26" class="column-noborder"></th>
                    <th><?php echo My_View_Helper_Html::UrlOrderBy('contact_name', $this->translate('Nom du contact')); ?></th>
                    <th width="200"><span class="notsortable"><?php echo $this->translate('Télephone'); ?></span></th>
                    <th width="250"><?php echo My_View_Helper_Html::UrlOrderBy('ct_email', $this->translate('E-mail')); ?></th>
                    <th width="15%"><span class="notsortable"><?php echo $this->translate('Site de rattachement'); ?></span></th>
                    <th><span class="notsortable"><?php echo $this->translate('Fonction du contact'); ?></span></th>
                    <th width="220"><span class="notsortable"><?php echo $this->translate('Opérations relatives'); ?></span></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $contact) {
                    ?>
                    <tr class="<?php echo $this->cycle(array('', 'alt'))->next() ?>">
                        <td><a href="#delete" class="icon-list icon-delete" ct_id="<?php echo $contact['ct_id']; ?>" title="<?php echo $this->translate('Basculer le statut du contact (actif/inactif)'); ?>"><?php echo $this->translate('Basculer le statut du contact'); ?></a></td>
                        <td><a href="javascript:void(0)" class="icon-list icon-edit" ct_id="<?php echo $contact['ct_id']; ?>" title="<?php echo $this->translate('Modifier le contact'); ?>"><?php echo $this->translate('Modifier le contact'); ?></a></td>
                        <td align="center"><?php echo Phoenix_View_Helper_Html::getContactStatusIcon($contact['actif']); ?></td>
                        <td><?php echo mb_convert_case($contact['ct_lastname'], MB_CASE_UPPER, "UTF-8") . ' ' . mb_convert_case($contact['ct_firstname'], MB_CASE_TITLE, "UTF-8"); ?></td>
                        <td><?php echo $contact['ct_phone']; ?></td>
                        <td><a href="mailto:<?php echo $contact['ct_email']; ?>"><?php echo $contact['ct_email']; ?></a></td>
                        <td><?php echo $contact['cl_site_libelle']; ?></td>
                        <td><?php echo $contact['ct_title'] ?></td>
                        <td>
                            <?php if ($contact['nb_operations'] > 0) { ?>
                                <a href="<?php echo $this->url(array('module' => 'operation', 'controller' => 'listing', 'action' => 'index', 'findbyfields' => "Rechercher", 'find_op_ct_id' => $contact['ct_id'])) ?>">
                                    <?php echo $this->translate('Voir les opérations du contact'); ?> (<?php echo $contact['nb_operations']; ?>)
                                </a>
                            <?php } else { ?>
                                <?php echo $this->translate('Pas d\'opérations'); ?>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<div id="id_dialog_search" title="<?php echo $this->translate('Recherche avancée'); ?>" style="display:none;">
    <form action="<?php echo $this->BaseUrl() ?>/client/contact/client/cl_id/<?php echo $this->cl_id; ?>" method="get" style="border:1px black">
        <div class="line form-line">
            <label class="unit size1of2 form-label" for="id_find_ct_lastname"><?php echo $this->translate('Nom du contact'); ?> :</label>
            <?php echo Phoenix_View_Helper_Html::input(array('name' => 'find_ct_lastname', 'class' => 'form-input unit size1of2 lastUnit')); ?>
        </div>

        <div class="line form-line">
            <label class="unit size1of2 form-label" for="id_find_ct_firstname"><?php echo $this->translate('Prénom du contact'); ?> :</label>
            <?php echo Phoenix_View_Helper_Html::input(array('name' => 'find_ct_firstname', 'class' => 'form-input unit size1of2 lastUnit')); ?>
        </div>

        <div class="line form-line">
            <label class="unit size1of2 form-label" for="id_find_ct_email"><?php echo $this->translate('E-mail'); ?> :</label>
            <?php echo Phoenix_View_Helper_Html::input(array('name' => 'find_ct_email', 'class' => 'form-input unit size1of2 lastUnit')); ?>
        </div>
        <?php                                                
        // Disable newsletter, not used at the moment                                                
        /**
        <div class="line form-line">
            <?php echo Phoenix_View_Helper_Html::checkbox(array('value' => '1', 'name' => 'find_ct_newsletter', 'class' => '')); ?>
            <label for="id_find_ct_newsletter"><?php echo $this->translate('Inscription Newsletter'); ?></label>
        </div>**/
        ?>

        <div class="line form-line">
            <?php echo Phoenix_View_Helper_Html::checkbox(array('value' => '0', 'name' => 'find_actif', 'class' => '')); ?>
            <label for="id_find_actif"><?php echo $this->translate('Contact inactif'); ?></label>
        </div>

        <div class="text-center">
            <input type="submit" name="findbyfields" value="Rechercher" class="btn btn-orange">
        </div>
        <input type="hidden" name="cl_id" value="<?php echo $this->cl_id; ?>" />
    </form>
</div>


<script language="javascript">
    $(document).ready(function () {
        /**
         * DIALOG / AJOUTER CONTACT
         */
        $('#id_btn_ajout_contact').live('click', function (e) {
            AjaxComponent.ajaxDialog(baseUrl + '/client/contact/update', {cl_id: <?php echo $this->cl_id; ?>}, {width: '500', title: 'Créer un nouveau contact', id: 'id_dialog_update_contact'})
        }
        );

        /**
         * DIALOG / MODIFIER CONTACT
         */
        $('.list .icon-edit').live('click', function (e) {
            ct_id = $(this).attr("ct_id");
            AjaxComponent.ajaxDialog(baseUrl + '/client/contact/update', {ct_id: ct_id}, {width: '500', title: 'Modifier le contact', id: 'id_dialog_update_contact'});
        });

        /**
         * DIALOG / SWITCH STATUS CONTACT
         */
        $('.list .icon-delete').live('click', function (e) {
            ct_id = $(this).attr("ct_id");

            AjaxComponent.ajaxQuery(baseUrl + '/client/contact/switchstatus', 'ct_id=' + ct_id)
                    .success(function (data) {
                        Component.refreshPage();
                    });
        });

        /**
         * DIALOG / RECHERCHE CONTACT
         */
        $('#btn_adsearch').click(function (e) {
            $('#id_dialog_search').dialog({
                width: 400,
                modal: true,
                resizable: false
            });
        });
    });
</script>